### ISSUE TITLE
knora-reset-triplestore fails because of wrong path

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/dsp-tools#15]
`knora-reset-triplestore` fails with this exception:

```
org.knora.webapi.BadRequestException: File /Users/benjamingeer/git/knora-api/webapi/./knora-ontologies/knora-admin.ttl does not exist
```

The path is incorrect; `knora-ontologies` is under `knora-api`, not under `knora-api/webapi`.

**Comment by subotic** [comment]
I don't think that I got `knora-reset-triplestore` ever working. The easiest would be for you to use the usual `webapi/scripts`.
