### ISSUE TITLE
StillImageRepresentation uploaded by knora-xml-import cannot be displayed in Salsah 1.5

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/dsp-tools#21]
Using knora on `develop` and running the `knora-xml-import` script with images as described in the doc results in an error in Salsah 1.5 and Knora API.

If a resource is a subclass of `knora-base:StillImageRepresentation`, even though the import with `knora-xml-import` went smoothly, I cannot display the resource at all. I got a `500 Internal Server Error` and if a try to display the resource in the API (using  http://0.0.0.0:3333/v1/resources/http%3A%2F%2Frdfh.ch%2F00FE%2FuYkYMpHoRfe7O29TPBb-BA), then I got the following error:

`{"status":4,"error":"org.knora.webapi.InconsistentTriplestoreDataException: Unknown MIME type: image/jpx"}`

But I can display without any problem a resource if it is not a a subclass of `knora-base:StillImageRepresentation`.

It can be easily reproduced using the `test-data.xml`.

**Comment by mrivoal** [comment]
@lrosenth could you maybe have a look at this? (not very urgent though, but I'm planning to use the library for a full data import which will include images.)

**Comment by subotic** [comment]
Could you maybe try the same thing with https://github.com/dasch-swiss/knora-api/releases/tag/v10.1.1 and not `develop`?

After this commit, there where some changes involving Knora-Sipi integration. It would be good to know if this issue was introduced recently or if it was there for a longer time.

**Comment by subotic** [comment]
And thanks for reporting :-)

**Comment by mrivoal** [comment]
You were right. With this version of Knora, I am able to display a `StillImageRepresentation`.

**Comment by subotic** [comment]
So the question is, was a bug introduced in `knora-api` or a breaking change requiring changes to `knora-py`?

**Comment by subotic** [comment]
@benjamingeer @tobiasschweizer could you maybe take a look at this issue? In recent commits of `knora-api` there was either a bug introduced or a breaking change.

**Comment by subotic** [comment]
Has maybe to do with: https://github.com/dasch-swiss/knora-api/pull/1521

**Comment by subotic** [comment]
What happens if you access the resource with `v2`: http://0.0.0.0:3333/v2/resources/http%3A%2F%2Frdfh.ch%2F00FE%2FuYkYMpHoRfe7O29TPBb-BA

**Comment by tobiasschweizer** [comment]
I guess v2 allows for MIME types that v1 does not support:

https://github.com/dasch-swiss/knora-api/blob/4dad1d788c15a21c2d04bc2f14fc0081e638137a/webapi/src/main/scala/org/knora/webapi/responders/v1/ValueUtilV1.scala#L104-L125

`image/jpx` is not listed, only `image/jp2`.

**Comment by tobiasschweizer** [comment]
Maybe `image/jpx` could simply be added: see https://en.wikipedia.org/wiki/JPEG_2000, https://tools.ietf.org/html/rfc3745

**Comment by benjamingeer** [comment]
I think I had this problem too, and I solved it this way:

https://github.com/dasch-swiss/knora-api/pull/1233/files#diff-902f74f03286363fd8a94360df6c4753R109

**Comment by mrivoal** [comment]
@subotic I have finally tested the `/v2/resources` route. I get to see the complete description of the resource if I use this route instead of `v1`.

**Comment by loicjaouen** [comment]
@benjamingeer so PR #1233 solves this issue? it should be in a coming release of `knora-api`, shouldn't it?

**Comment by benjamingeer** [comment]
@loicjaouen I don't know, I haven't looked at this issue myself. https://github.com/dasch-swiss/knora-api/pull/1233 is waiting for https://github.com/dasch-swiss/sipi/issues/309.

**Comment by tobiasschweizer** [comment]
If you need that urgently, why don't you just add the missing mimetype as suggested in https://github.com/dasch-swiss/knora-py/issues/21#issuecomment-564062545?
