### ISSUE TITLE
Main branch does not correspond to PyPi version

### ISSUE THREAD

**Issue by musicEnfanthen** [dasch-swiss/dsp-tools#35]
The latest version released on PyPi (0.9.12) has fixed the ModuleNotFoundError issue.

However, it is not reflected in the main branch of this repo, what is quite confusing.

**Comment by BalduinLandolt** [comment]
Release process is automated now. Starting with the next release,  PyPI and Github release should correspond, and reflect the main branch.  
(In other words: No confusion anymore... Hooray!)
