### ISSUE TITLE
docs(dsp-tools-create): guiattribute "maxlength" is of string type instead of integer in docs example

### ISSUE THREAD

**Issue by musicEnfanthen** [dasch-swiss/dsp-tools#39]
The [dsp-tools documentation](https://dasch-swiss.github.io/dsp-tools/dsp-tools-create/#object-gui_element-gui_attribute) mentions a `maxlength` gui-attribute that should be of type integer. However, in the docs example the attributes' values are of string type.

```
{
  "name": "hasPictureTitle",
  "super": [
    "hasValue"
  ],
  "object": "TextValue",
  "labels": {"en": "Title"},
  "gui_element": "SimpleText",
  "gui_attributes": {
    "maxlength": "255",
    "size": 80
  }
}
```

Related to #38

**Comment by irinaschubert** [comment]
We fixed this.

**Comment by musicEnfanthen** [comment]
Thank you
