### ISSUE TITLE
ValidationError: <property_name> does not match '^(([\\w-]*)?:([\\w ]+))$'

### ISSUE THREAD

**Issue by musicEnfanthen** [dasch-swiss/dsp-tools#40]
Related to dasch-swiss/salsah-migration-scripts/issues/10

**Comment by musicEnfanthen** [comment]
Should be safe to close. Property names in export scripts are validating correctly at the moment.

**Comment by irinaschubert** [comment]
Thanks for the reply, @musicEnfanthen . You are welcome to open new issues if new problems arise :)
