### ISSUE TITLE
[knora-api error] Creating property class failed. Invalid id: #dc:date

### ISSUE THREAD

**Issue by musicEnfanthen** [dasch-swiss/dsp-tools#44]
`dc:date` property in the model passed to `dsp-tools create ...` fails with the following error message:

```
Creating property class failed: KNORA-ERROR: status code=400
Message:{"knora-api:error":"org.knora.webapi.exceptions.BadRequestException: Invalid @id: http://api.0
806-test-server.dasch.swiss/ontology/0806/webern/v2#dc:date","@context":{"knora-api":"http://api.knora
.org/ontology/knora-api/v2#"}}
```

Already added `dc` to the prefixes section, but to no avail.

Ping @lrosenth

**Comment by musicEnfanthen** [comment]
Workaround for now according to @lrosenth until there is a solution for this issue implemented in the backend:

Do not use `dc:date` directly, but rebuild it as a "project-internal" property `dc_date` which has as a super value `dc:date`:
```

{
    "name": "dc_date",
    "super": [
        "hasValue",
        "dc:date"
    ],
    "object": "DateValue",
    "labels": {
        "de": "Dublin Core Date"
    },
    "comments": {
        "de": "Data according dublin core"
    },
    "gui_element": "Date",
    "gui_attributes": {}
},
```

It can then be addressed from the resource definitions as follows:
```
{
    "propname": ":dc_date",
    "cardinality": "0-1"
}
```

**Comment by irinaschubert** [comment]
Hi @musicEnfanthen , is this issue still open for you?

**Comment by musicEnfanthen** [comment]
Thanks for checking. I guess with the `super` mechanism described above, it works for now. Can be closed.

**Comment by irinaschubert** [comment]
OK, thanks for the response, I then close it.
