### ISSUE TITLE
While creating the ontology, a user and project permissions should also be created

### ISSUE THREAD

**Issue by subotic** [dasch-swiss/dsp-tools#6]

**Comment by musicEnfanthen** [comment]
@irinaschubert This issue is addressed in #127, too?

**Comment by irinaschubert** [comment]
This was not addressed in #127 but works now as far as I know. With creation of a user did you mean that you can define a user in the ontology JSON which is then created when using `dsp-tools create`? And with project permissions did you mean that a user can be added to a project (as member or project admin) in the ontology JSON? If so, both things work now.

**Comment by musicEnfanthen** [comment]
I don't know about the details of the issue here, since it was created by @subotic. Maybe he can tell more? (I was just stumbling over it while browsing through the issue list.)

**Comment by irinaschubert** [comment]
Hi @musicEnfanthen , I checked it with Ivan and this is solved. I hereby close the issue.
