### ISSUE TITLE
docs: How to create a list with knora-py?

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/dsp-tools#7]
We are trying to use the library to create only list.

However, following the doc we get an error while launching `python3 create_ontology.py -l list.json`:

```
File "create_ontology.py", line 6, in <module>
    from jsonschema import validate
ModuleNotFoundError: No module named 'jsonschema'
```

Do we have to configure something?

**Comment by subotic** [comment]
It seems that the `jsonschema` python module is missing `pip3 install jsonschema` should fix this.

Strange that it didn't install it.

Did you install `knora-py` recently? Could you please try: `pip3 install -U knora-py`.

**Comment by subotic** [comment]
Which version of `knora-py` do you have installed? To check, please run: `pip3 show knora`.

**Comment by subotic** [comment]
Or are you running from source?

**Comment by mrivoal** [comment]
Yes, we were running from source. This point is not very clear in the doc.

We will try to run it from your library.

**Comment by mrivoal** [comment]
After installing `pip3 install -U knora`,  I just did 
```
python3 create_ontology.py -l list.json 
```
But it looks like nothing is happening. `list.json` uses the existing project `anything`.

The version of `knora-py` is 0.0.5.

**Comment by mrivoal** [comment]
We finally got there, by launching
```
$ knora-create-ontology -l list.json 
```

**Comment by subotic** [comment]
great, that you managed to get it working. yes, the docs need "some" work ;-)
