### ISSUE TITLE
Would it be possible to assign IRIs for rootnodes using knora-py?

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/dsp-tools#8]
Because lists `rootnodes` are refered to in project-specific ontologies which makes the process of creating a project ontology together with its lists very cumbersome.

Each time a list changes (which happens quite often in the modelling/design phase) and has to be send to the API via knora-py, the corresponding `rootnode` will have to be updated in the ontology. A workaround would be to give the user the possibility to define IRIs for `rootnodes`. Would it be possible?

---

needs dhlab-basel/Knora#1305

**Comment by subotic** [comment]
So you just create the list with `knora-py` and not the ontology?

**Comment by mrivoal** [comment]
Exactly, yes. This is what I do, because I am used to handle an ontology in .ttl and this is my reference until now for all the modeling phase. I may switch at some point to the .json-ld converted into a proper .ttl (as discussed in #1288), but right now, it is more straightforward for me to use the .ttl.

If knora-py can be used to create lists only, then maybe having to possibility to assign an IRIs to a `rootnode` is an accurate feature? What do you think?

**Comment by subotic** [comment]
In any way, `knora-py` is using the admin api to create the lists, which does not yet allow to create a list or list items by supplying your own IRIs.

I will add it, but I cannot make any promises on when it is going happen.

**Comment by subotic** [comment]
> If knora-py can be used to create lists only, then maybe having to possibility to assign an IRIs to a rootnode is an accurate feature? What do you think?

Yes, definitely.

**Comment by mrivoal** [comment]
> I will add it, but I cannot make any promises on when it is going happen.

I will do without for a while, don't worry. I have lived until now without knora-py :)

**Comment by mrivoal** [comment]
And thanks!

**Comment by SepidehAlassi** [comment]
@mrivoal In knora-Api, this is implemented in [PR #1654](https://github.com/dasch-swiss/knora-api/pull/1654)

**Comment by mrivoal** [comment]
@SepidehAlassi Thank you very much! I will have a need for it very soon.
