### ISSUE TITLE
Validation broken in v1.4.1

### ISSUE THREAD

**Issue by musicEnfanthen** [dasch-swiss/dsp-tools#98]
Hi @BalduinLandolt and @irinaschubert ,

With the latest version update, the schema validation with dsp-tools is broken here.

`dsp-tools create project.json --validate` throws the following error:

```
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.9.7/x64/bin/dsp-tools", line 8, in <module>
    sys.exit(main())
  File "/Users/runner/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/knora/dsp_tools.py", line 164, in main
    program(sys.argv[1:])
  File "/Users/runner/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/knora/dsp_tools.py", line 125, in program
    validate_ontology(args.datamodelfile)
  File "/Users/runner/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/knora/dsplib/utils/onto_validate.py", line 42, in validate_ontology
    with open(os.path.join(current_dir, '../schemas/ontology.json')) as s:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/runner/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/knora/dsplib/utils/../schemas/ontology.json'
```

Seems that the path.join does not create the path correctly? (Cf. https://stackoverflow.com/a/21006000)

**Comment by irinaschubert** [comment]
Hi @musicEnfanthen , thank you for reporting the issue. The path was correct but the file was missing inside the build. The validation works again now, please update dsp-tools to the latest version.

**Comment by musicEnfanthen** [comment]
Hi @irinaschubert . Thank you for the fix. Now it finds the file, but fails while validating with the following error:

```
'$schema' is a required property

Failed validating 'required' in schema:
    {'$id': 'https://dasch.swiss/schema/ontology.json',
     '$schema': 'https://json-schema.org/draft/2020-12/schema',
     'additionalProperties': False,
     'definitions': {'cardinality': {'additionalProperties': False,
```

See https://github.com/webern-unibas-ch/migration-scripts/runs/3671634091?check_suite_focus=true#step:12:13

Do I need to add $schema and $id to our created JSON data model file?

**Comment by irinaschubert** [comment]
Hi @musicEnfanthen , yes, exactly, this is new. You have to add the following line to the top level of your data model:
`"$schema": "https://raw.githubusercontent.com/dasch-swiss/dsp-tools/main/knora/dsplib/schemas/ontology.json",`

You also need to add the following to the `knora` node of the XML for data upload (with your shortcode and name of the ontology):
```
<knora xmlns="https://dasch.swiss/schema"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://dasch.swiss/schema https://raw.githubusercontent.com/dasch-swiss/dsp-tools/main/knora/dsplib/schemas/data.xsd"
       shortcode="...."
       default-ontology="...">
```
I will add this to our documentation today.

**Comment by musicEnfanthen** [comment]
Thank you very much, @irinaschubert . Yes, works again with the included $schema line: https://github.com/webern-unibas-ch/migration-scripts/runs/3672238939?check_suite_focus=true

BTW, the validation issue above with the missing $schema did not throw an actual error, i.e. the script ran through "successfully". Maybe it could be helpful if there is something like a break or exit if validation fails?

**Comment by irinaschubert** [comment]
Hi @musicEnfanthen , thank you for the response and your suggestion. In the newest release of dsp-tools, an exit code of 1 is returned if the schema validation fails.

**Comment by musicEnfanthen** [comment]
Great, thank you very much, @irinaschubert !
